### ISSUE TITLE
read later

### ISSUE THREAD

**Issue by km-tr** [yasuyk/Pinboard-Chrome-Extension#1] opened 2013-04-15 13:05 UTC
read later url failed

**Comment by yasuyk** [comment] 2013-05-26 18:26
Hi, @baruok. Sorry for the delay in responding.
Please tell me more infomation about read later uri failed.
I haven't seen this problem on my site.

**Comment by wulfovitch** [comment] 2013-05-28 14:44
I had the same issue at the time, this topic was created. Now the issue is gone. I suppose, it was a change on the pinboard server side which caused the error and is now fixed.

**Comment by km-tr** [comment] 2013-05-29 10:26
It is as he said.
Thare is another problem.
“Save to pinboard” don't react with keyboard shortacut and click.
Option tab of chrome app keycofig only react it.

**Comment by yasuyk** [comment] 2013-05-29 13:53
Hi @wulfovitch. Thanks for information.
I wonder if that cause is [Little Green Locks](https://blog.pinboard.in/2013/04/little_green_locks/).

**Comment by yasuyk** [comment] 2013-05-29 14:44
@baruok 

> “Save to pinboard” don't react with keyboard shortacut and click.
> Option tab of chrome app keycofig only react it.

Hmmm... it is also same. I haven't seen on my site.
Please tell me the following questions.
1. Is there the problem still?
2. When the problem occurs, Does Official bookmarklets work?
   
   See below URL about Official bookmarklets.
   https://pinboard.in/howto/#saving
3. Do Other features work (such as All bookmarks or Unread bookmarks)?
4. What chrome version do you use?

Thanks

**Comment by km-tr** [comment] 2013-05-31 15:15
@yasuyk 
1. Yes.
2. Yes.
3. Yes. They work well.
4. My chrome version is 28.0.1500.29 beta-m
   This feature work on normal new tab page.
   Keyconfig disabled, but its change is none.

**Comment by yasuyk** [comment] 2013-06-01 03:12
Thanks for answering all my questions, I reproduce the problem on my site.
The problem occurs only with Chrome 28 beta.

The problem is not suitable whit issue title, so I open [new issue](2) and close this issue.

Thanks

**Closed as completed by yasuyk** 2013-06-01 03:12 UTC
